name: greenspace
description: A sample web application
dependencies:
  browser: any
  google_maps: '>=2.0.0 <3.0.0'
  paper_elements: '>=0.0.1 <0.1.0'
  polymer: '>=0.11.0 <0.12.0'
  xml: '>=2.0.0 <3.0.0'
transformers:
- polymer:
    entry_points: web/greenspace.html
